### PR TITLE
Update runtime to 42

### PR DESCRIPTION
**Pull request by bbhtt**
sphinxbase is deprecated and per the readme integrated into pocketsphinx but looks like they don't have a stable release.

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
> Build [107820 failed](https://buildbot.flathub.org/#/builders/32/builds/107820)

Bazel is trying to download packages

```
WARNING: Download from https://mirror.bazel.build/openjdk/azul-zulu11.50.19-ca-jdk11.0.12/zulu11.50.19-ca-jdk11.0.12-linux_x64.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: mirror.bazel.build
Analyzing: target //src:bazel_nojdk (368 packages loaded, 9319 targets configu\
red)
ERROR: An error occurred during the fetch of repository 'remotejdk11_linux':
   Traceback (most recent call last):
	File "/tmp/bazel_vI89r2Ht/out/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu11.50.19-ca-jdk11.0.12/zulu11.50.19-ca-jdk11.0.12-linux_x64.tar.gz] to /tmp/bazel_vI89r2Ht/out/external/remotejdk11_linux/temp131881174444891678/zulu11.50.19-ca-jdk11.0.12-linux_x64.tar.gz: Unknown host: mirror.bazel.build
Analyzing: target //src:bazel_nojdk (368 packages loaded, 9319 targets configu\
red)
ERROR: /DEFAULT.WORKSPACE.SUFFIX:41:6: fetching http_archive rule //external:remotejdk11_linux: Traceback (most recent call last):
	File "/tmp/bazel_vI89r2Ht/out/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu11.50.19-ca-jdk11.0.12/zulu11.50.19-ca-jdk11.0.12-linux_x64.tar.gz] to /tmp/bazel_vI89r2Ht/out/external/remotejdk11_linux/temp131881174444891678/zulu11.50.19-ca-jdk11.0.12-linux_x64.tar.gz: Unknown host: mirror.bazel.build
```

**Comment by bbhtt** [comment]
> Started [test build 107843](https://buildbot.flathub.org/#/builders/32/builds/107843)

```
Running: cd tensorflow-r2.3/; bazel --output_user_root=/run/ccache/bazel build --distdir=../bazel-distdir --override_repository=io_bazel_rules_go=/run/build/deepspeech/rules_go-0.23.15 --override_repository=com_github_nelhage_rules_boost=/run/build/deepspeech/rules_boost-1e3a69bf2d5cd10c34b74f066054cd335d033d71 --override_repository=io_bazel_rules_docker=/run/build/deepspeech/rules_docker-0.15.0 --workspace_status_command='bash native_client/bazel_workspace_status_cmd.sh' --config=monolithic --config=noaws -c opt --copt=-O3 --copt='-D_GLIBCXX_USE_CXX11_ABI=0' --copt=-fvisibility=hidden //native_client:libdeepspeech.so
FB: Running 'flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/deepspeech --nofilesystem=host:reset --filesystem=/srv/buildbot/worker/build-x86_64-3/build/.flatpak-builder/build/deepspeech-1 --bind-mount=/run/build/deepspeech=/srv/buildbot/worker/build-x86_64-3/build/.flatpak-builder/build/deepspeech-1 --build-dir=/run/build/deepspeech --bind-mount=/run/ccache=/srv/buildbot/worker/build-x86_64-3/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1662169891 '--env=CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ' --env=PREFIX=/app --env=TFDIR=../tensorflow-r2.3/ --env=JAVA_HOME=/usr/lib/sdk/openjdk11/jvm/openjdk-11 --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=48 /srv/buildbot/worker/build-x86_64-3/build/.flatpak-builder/rofiles/rofiles-d6P2fS /bin/sh -c 'cd tensorflow-r2.3/; bazel --output_user_root=/run/ccache/bazel build --distdir=../bazel-distdir --override_repository=io_bazel_rules_go=/run/build/deepspeech/rules_go-0.23.15 --override_repository=com_github_nelhage_rules_boost=/run/build/deepspeech/rules_boost-1e3a69bf2d5cd10c34b74f066054cd335d033d71 --override_repository=io_bazel_rules_docker=/run/build/deepspeech/rules_docker-0.15.0 --workspace_status_command='\''bash native_client/bazel_workspace_status_cmd.sh'\'' --config=monolithic --config=noaws -c opt --copt=-O3 --copt='\''-D_GLIBCXX_USE_CXX11_ABI=0'\'' --copt=-fvisibility=hidden //native_client:libdeepspeech.so'' on host
file is invalid or corrupted (missing end of central directory record)
Opening zip "/app/bin/bazel": Cannot find central directory
FATAL: Failed to open '/app/bin/bazel' as a zip file: (error: 5): Input/output error
```

Not sure why it's looking for the zip, the bazel binary should only be needed.

**Comment by bbhtt** [comment]
Seems like newer bazel is creating problems and I can't figure out how to deal with them. So I reverted back to 3.1.0 and picked a patch to fix build with newer gcc. Hopefully that should be enough. If anyone has any better idea on applying the patch or figuring out the build with newer bazel, please let me know.

**Comment by bbhtt** [comment]
> Build [107974 failed](https://buildbot.flathub.org/#/builders/32/builds/107974)

```
Running: cd tensorflow-r2.3/; bazel --output_user_root=/run/ccache/bazel build --distdir=../bazel-distdir --override_repository=io_bazel_rules_go=/run/build/deepspeech/rules_go-0.23.15 --override_repository=com_github_nelhage_rules_boost=/run/build/deepspeech/rules_boost-1e3a69bf2d5cd10c34b74f066054cd335d033d71 --override_repository=io_bazel_rules_docker=/run/build/deepspeech/rules_docker-0.15.0 --workspace_status_command='bash native_client/bazel_workspace_status_cmd.sh' --config=monolithic --config=noaws -c opt --copt=-O3 --copt='-D_GLIBCXX_USE_CXX11_ABI=0' --copt=-fvisibility=hidden //native_client:libdeepspeech.so
FB: Running 'flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/deepspeech --nofilesystem=host:reset --filesystem=/srv/buildbot/worker/build-x86_64-6/build/.flatpak-builder/build/deepspeech-1 --bind-mount=/run/build/deepspeech=/srv/buildbot/worker/build-x86_64-6/build/.flatpak-builder/build/deepspeech-1 --build-dir=/run/build/deepspeech --bind-mount=/run/ccache=/srv/buildbot/worker/build-x86_64-6/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1662222467 '--env=CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ' --env=PREFIX=/app --env=TFDIR=../tensorflow-r2.3/ --env=JAVA_HOME=/usr/lib/sdk/openjdk11/jvm/openjdk-11 --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=48 /srv/buildbot/worker/build-x86_64-6/build/.flatpak-builder/rofiles/rofiles-WSI3hA /bin/sh -c 'cd tensorflow-r2.3/; bazel --output_user_root=/run/ccache/bazel build --distdir=../bazel-distdir --override_repository=io_bazel_rules_go=/run/build/deepspeech/rules_go-0.23.15 --override_repository=com_github_nelhage_rules_boost=/run/build/deepspeech/rules_boost-1e3a69bf2d5cd10c34b74f066054cd335d033d71 --override_repository=io_bazel_rules_docker=/run/build/deepspeech/rules_docker-0.15.0 --workspace_status_command='\''bash native_client/bazel_workspace_status_cmd.sh'\'' --config=monolithic --config=noaws -c opt --copt=-O3 --copt='\''-D_GLIBCXX_USE_CXX11_ABI=0'\'' --copt=-fvisibility=hidden //native_client:libdeepspeech.so'' on host
file is invalid or corrupted (missing end of central directory record)
Opening zip "/proc/self/exe": Cannot find central directory
FATAL: Failed to open '/proc/self/exe' as a zip file: (error: 5): Input/output error
FB: host_command_exited_cb 1702311 9216
```

Searching the error online, it seems the solution is to prevent debuginfo stripping from the bazel binary but that's already being done. So not sure what more is needed.

**Comment by gkarsay** [comment]
Thank you for trying and I'm sorry you couldn't finish it. I had myself troubles building DeepSpeech and later on I failed updating it with a new toolchain. I don't have the resources to finish this or to maintain DeepSpeech support therefore I decided to drop it. Especially since DeepSpeech isn't actively developed anymore. Anyway, thank you for your efforts.

**Pull request closed without merging**
